"""postgresql baseline

Revision ID: 202603310001
Revises: 
Create Date: 2026-03-31 23:40:35.715153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202603310001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_apps',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_id', sa.Text(), nullable=True),
    sa.Column('secret_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_apps_deleted'), 'acl_apps', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_apps_name'), 'acl_apps', ['name'], unique=False)
    op.create_table('users',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('catalog', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('secret', sa.String(length=32), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('block', sa.Boolean(), nullable=True),
    sa.Column('has_logined', sa.Boolean(), nullable=True),
    sa.Column('wx_id', sa.String(length=32), nullable=True),
    sa.Column('employee_id', sa.String(length=16), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_deleted'), 'users', ['deleted'], unique=False)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_table('acl_audit_login_logs',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.Enum('web', 'api', 'ssh', native_enum=False), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('browser', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('is_ok', sa.Boolean(), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_audit_login_logs_created_at'), 'acl_audit_login_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_acl_audit_login_logs_username'), 'acl_audit_login_logs', ['username'], unique=False)
    op.create_table('acl_audit_permission_logs',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('operate_uid', sa.Integer(), nullable=True, comment='操作人uid'),
    sa.Column('operate_type', sa.String(length=16), nullable=True, comment='操作类型'),
    sa.Column('rid', sa.Integer(), nullable=True, comment='角色id'),
    sa.Column('resource_type_id', sa.Integer(), nullable=True, comment='资源类型id'),
    sa.Column('resource_ids', sa.JSON(), nullable=True, comment='资源'),
    sa.Column('group_ids', sa.JSON(), nullable=True, comment='资源组'),
    sa.Column('permission_ids', sa.JSON(), nullable=True, comment='权限'),
    sa.Column('source', sa.String(length=16), nullable=True, comment='来源'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_audit_permission_logs_app_id'), 'acl_audit_permission_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_permission_logs_deleted'), 'acl_audit_permission_logs', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_audit_permission_logs_operate_type'), 'acl_audit_permission_logs', ['operate_type'], unique=False)
    op.create_index(op.f('ix_acl_audit_permission_logs_operate_uid'), 'acl_audit_permission_logs', ['operate_uid'], unique=False)
    op.create_index(op.f('ix_acl_audit_permission_logs_resource_type_id'), 'acl_audit_permission_logs', ['resource_type_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_permission_logs_rid'), 'acl_audit_permission_logs', ['rid'], unique=False)
    op.create_table('acl_audit_resource_logs',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('operate_uid', sa.Integer(), nullable=True, comment='操作人uid'),
    sa.Column('operate_type', sa.String(length=16), nullable=True, comment='操作类型'),
    sa.Column('scope', sa.String(length=16), nullable=True, comment='范围'),
    sa.Column('link_id', sa.Integer(), nullable=True, comment='资源名'),
    sa.Column('origin', sa.JSON(), nullable=True, comment='原始数据'),
    sa.Column('current', sa.JSON(), nullable=True, comment='当前数据'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='权限名'),
    sa.Column('source', sa.String(length=16), nullable=True, comment='来源'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_audit_resource_logs_app_id'), 'acl_audit_resource_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_resource_logs_deleted'), 'acl_audit_resource_logs', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_audit_resource_logs_link_id'), 'acl_audit_resource_logs', ['link_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_resource_logs_operate_type'), 'acl_audit_resource_logs', ['operate_type'], unique=False)
    op.create_index(op.f('ix_acl_audit_resource_logs_operate_uid'), 'acl_audit_resource_logs', ['operate_uid'], unique=False)
    op.create_table('acl_audit_role_logs',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('operate_uid', sa.Integer(), nullable=True, comment='操作人uid'),
    sa.Column('operate_type', sa.String(length=32), nullable=True, comment='操作类型'),
    sa.Column('scope', sa.String(length=16), nullable=True, comment='范围'),
    sa.Column('link_id', sa.Integer(), nullable=True, comment='资源id'),
    sa.Column('origin', sa.JSON(), nullable=True, comment='原始数据'),
    sa.Column('current', sa.JSON(), nullable=True, comment='当前数据'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='其他内容'),
    sa.Column('source', sa.String(length=16), nullable=True, comment='来源'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_audit_role_logs_app_id'), 'acl_audit_role_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_role_logs_deleted'), 'acl_audit_role_logs', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_audit_role_logs_link_id'), 'acl_audit_role_logs', ['link_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_role_logs_operate_type'), 'acl_audit_role_logs', ['operate_type'], unique=False)
    op.create_index(op.f('ix_acl_audit_role_logs_operate_uid'), 'acl_audit_role_logs', ['operate_uid'], unique=False)
    op.create_table('acl_audit_trigger_logs',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True, comment='trigger'),
    sa.Column('operate_uid', sa.Integer(), nullable=True, comment='操作人uid'),
    sa.Column('operate_type', sa.String(length=16), nullable=True, comment='操作类型'),
    sa.Column('origin', sa.JSON(), nullable=True, comment='原始数据'),
    sa.Column('current', sa.JSON(), nullable=True, comment='当前数据'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='权限名'),
    sa.Column('source', sa.String(length=16), nullable=True, comment='来源'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_audit_trigger_logs_app_id'), 'acl_audit_trigger_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_acl_audit_trigger_logs_deleted'), 'acl_audit_trigger_logs', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_audit_trigger_logs_operate_type'), 'acl_audit_trigger_logs', ['operate_type'], unique=False)
    op.create_index(op.f('ix_acl_audit_trigger_logs_operate_uid'), 'acl_audit_trigger_logs', ['operate_uid'], unique=False)
    op.create_index(op.f('ix_acl_audit_trigger_logs_trigger_id'), 'acl_audit_trigger_logs', ['trigger_id'], unique=False)
    op.create_table('acl_operation_records',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app', sa.String(length=32), nullable=True),
    sa.Column('rolename', sa.String(length=32), nullable=True),
    sa.Column('operate', sa.Enum('0', '1', '2', '3', '4', native_enum=False), nullable=False),
    sa.Column('obj', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_operation_records_app'), 'acl_operation_records', ['app'], unique=False)
    op.create_index(op.f('ix_acl_operation_records_deleted'), 'acl_operation_records', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_operation_records_rolename'), 'acl_operation_records', ['rolename'], unique=False)
    op.create_table('c_ad_counter',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('rule_count', sa.Integer(), nullable=True),
    sa.Column('exec_target_count', sa.Integer(), nullable=True),
    sa.Column('instance_count', sa.Integer(), nullable=True),
    sa.Column('accept_count', sa.Integer(), nullable=True),
    sa.Column('this_month_count', sa.Integer(), nullable=True),
    sa.Column('this_week_count', sa.Integer(), nullable=True),
    sa.Column('last_month_count', sa.Integer(), nullable=True),
    sa.Column('last_week_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_counter_created_at'), 'c_ad_counter', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_ad_counter_type_id'), 'c_ad_counter', ['type_id'], unique=False)
    op.create_table('c_ad_exec_histories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_exec_histories_created_at'), 'c_ad_exec_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_ad_exec_histories_type_id'), 'c_ad_exec_histories', ['type_id'], unique=False)
    op.create_table('c_ad_rules',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Enum('agent', 'snmp', 'http', 'components', native_enum=False), nullable=True),
    sa.Column('is_inner', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_plugin', sa.Boolean(), nullable=True),
    sa.Column('plugin_script', sa.Text(), nullable=True),
    sa.Column('unique_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_rules_deleted'), 'c_ad_rules', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ad_rules_is_inner'), 'c_ad_rules', ['is_inner'], unique=False)
    op.create_index(op.f('ix_c_ad_rules_owner'), 'c_ad_rules', ['owner'], unique=False)
    op.create_index(op.f('ix_c_ad_rules_type'), 'c_ad_rules', ['type'], unique=False)
    op.create_table('c_attributes',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.Enum('0', '1', '2', '3', '4', '5', '6', '7', native_enum=False), nullable=False),
    sa.Column('is_choice', sa.Boolean(), nullable=True),
    sa.Column('is_list', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('is_index', sa.Boolean(), nullable=True),
    sa.Column('is_link', sa.Boolean(), nullable=True),
    sa.Column('is_password', sa.Boolean(), nullable=True),
    sa.Column('is_sortable', sa.Boolean(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('is_bool', sa.Boolean(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('reference_type_id', sa.Integer(), nullable=True),
    sa.Column('default', sa.JSON(), nullable=True),
    sa.Column('is_computed', sa.Boolean(), nullable=True),
    sa.Column('compute_expr', sa.Text(), nullable=True),
    sa.Column('compute_script', sa.Text(), nullable=True),
    sa.Column('choice_web_hook', sa.JSON(), nullable=True),
    sa.Column('choice_other', sa.JSON(), nullable=True),
    sa.Column('re_check', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_attributes_deleted'), 'c_attributes', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_attributes_uid'), 'c_attributes', ['uid'], unique=False)
    op.create_table('c_ci_type_groups',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_groups_deleted'), 'c_ci_type_groups', ['deleted'], unique=False)
    op.create_table('c_ci_type_histories',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operate_type', sa.Enum('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', name='operate_type', native_enum=False), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('rc_id', sa.Integer(), nullable=True),
    sa.Column('unique_constraint_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('change', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_histories_deleted'), 'c_ci_type_histories', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ci_type_histories_type_id'), 'c_ci_type_histories', ['type_id'], unique=False)
    op.create_index(op.f('ix_c_ci_type_histories_uid'), 'c_ci_type_histories', ['uid'], unique=False)
    op.create_table('c_ci_types',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=32), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_attached', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('default_order_attr', sa.String(length=33), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['unique_id'], ['c_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_types_deleted'), 'c_ci_types', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ci_types_uid'), 'c_ci_types', ['uid'], unique=False)
    op.create_foreign_key(
        'fk_c_attributes_reference_type_id_c_ci_types',
        'c_attributes',
        'c_ci_types',
        ['reference_type_id'],
        ['id'],
    )
    op.create_table('c_dcim_operation_histories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('ci_id', sa.Integer(), nullable=True),
    sa.Column('operate_type', sa.Enum('0', '1', '2', native_enum=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_dcim_operation_histories_ci_id'), 'c_dcim_operation_histories', ['ci_id'], unique=False)
    op.create_index(op.f('ix_c_dcim_operation_histories_created_at'), 'c_dcim_operation_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_dcim_operation_histories_rack_id'), 'c_dcim_operation_histories', ['rack_id'], unique=False)
    op.create_index(op.f('ix_c_dcim_operation_histories_uid'), 'c_dcim_operation_histories', ['uid'], unique=False)
    op.create_table('c_ipam_operation_histories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cidr', sa.String(length=18), nullable=True),
    sa.Column('operate_type', sa.Enum('0', '1', '2', '3', '4', '5', '6', '7', native_enum=False), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ipam_operation_histories_cidr'), 'c_ipam_operation_histories', ['cidr'], unique=False)
    op.create_index(op.f('ix_c_ipam_operation_histories_created_at'), 'c_ipam_operation_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_ipam_operation_histories_uid'), 'c_ipam_operation_histories', ['uid'], unique=False)
    op.create_table('c_ipam_subnet_scan_histories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subnet_scan_id', sa.Integer(), nullable=True),
    sa.Column('exec_id', sa.String(length=64), nullable=True),
    sa.Column('cidr', sa.String(length=18), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('ip_num', sa.Integer(), nullable=True),
    sa.Column('ips', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ipam_subnet_scan_histories_cidr'), 'c_ipam_subnet_scan_histories', ['cidr'], unique=False)
    op.create_index(op.f('ix_c_ipam_subnet_scan_histories_created_at'), 'c_ipam_subnet_scan_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_ipam_subnet_scan_histories_exec_id'), 'c_ipam_subnet_scan_histories', ['exec_id'], unique=False)
    op.create_index(op.f('ix_c_ipam_subnet_scan_histories_subnet_scan_id'), 'c_ipam_subnet_scan_histories', ['subnet_scan_id'], unique=False)
    op.create_table('c_ipam_subnet_scans',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('scan_enabled', sa.Boolean(), nullable=True),
    sa.Column('rule_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_time', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.String(length=8), nullable=True),
    sa.Column('cron', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ipam_subnet_scans_agent_id'), 'c_ipam_subnet_scans', ['agent_id'], unique=False)
    op.create_index(op.f('ix_c_ipam_subnet_scans_ci_id'), 'c_ipam_subnet_scans', ['ci_id'], unique=False)
    op.create_index(op.f('ix_c_ipam_subnet_scans_deleted'), 'c_ipam_subnet_scans', ['deleted'], unique=False)
    op.create_table('c_kv',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_kv_deleted'), 'c_kv', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_kv_key'), 'c_kv', ['key'], unique=False)
    op.create_table('c_pasc',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('base_strategy', sa.Enum('all', 'none', native_enum=False), nullable=False),
    sa.Column('group_ids', sa.JSON(), nullable=True),
    sa.Column('type_ids', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_pasc_deleted'), 'c_pasc', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_pasc_uid'), 'c_pasc', ['uid'], unique=True)
    op.create_table('c_prv',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cr_ids', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_prv_deleted'), 'c_prv', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_prv_name'), 'c_prv', ['name'], unique=False)
    op.create_index(op.f('ix_c_prv_uid'), 'c_prv', ['uid'], unique=False)
    op.create_table('c_records',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=True),
    sa.Column('ticket_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_records_created_at'), 'c_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_records_type_id'), 'c_records', ['type_id'], unique=False)
    op.create_index(op.f('ix_c_records_uid'), 'c_records', ['uid'], unique=False)
    op.create_table('c_relation_types',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_relation_types_deleted'), 'c_relation_types', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_relation_types_name'), 'c_relation_types', ['name'], unique=False)
    op.create_table('c_sc',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_sc_deleted'), 'c_sc', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_sc_name'), 'c_sc', ['name'], unique=False)
    op.create_table('c_topology_view_groups',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_topology_view_groups_deleted'), 'c_topology_view_groups', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_topology_view_groups_name'), 'c_topology_view_groups', ['name'], unique=False)
    op.create_table('common_company_info_json',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_company_info_json_deleted'), 'common_company_info_json', ['deleted'], unique=False)
    op.create_table('common_data',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_data_deleted'), 'common_data', ['deleted'], unique=False)
    op.create_table('common_department',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('department_director_id', sa.Integer(), nullable=True),
    sa.Column('department_parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_value', sa.Integer(), nullable=True),
    sa.Column('acl_rid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_common_department_deleted'), 'common_department', ['deleted'], unique=False)
    op.create_table('common_file',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('origin_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('binary', sa.LargeBinary(length=16777216), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_file_deleted'), 'common_file', ['deleted'], unique=False)
    op.create_index(op.f('ix_common_file_file_name'), 'common_file', ['file_name'], unique=False)
    op.create_table('common_notice_config',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=255), nullable=False),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_notice_config_deleted'), 'common_notice_config', ['deleted'], unique=False)
    op.create_table('acl_resource_types',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_resource_types_deleted'), 'acl_resource_types', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_resource_types_name'), 'acl_resource_types', ['name'], unique=False)
    op.create_table('acl_roles',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_app_admin', sa.Boolean(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('secret', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_roles_deleted'), 'acl_roles', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_roles_name'), 'acl_roles', ['name'], unique=False)
    op.create_table('c_ad_accounts',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('adr_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['adr_id'], ['c_ad_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_accounts_deleted'), 'c_ad_accounts', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ad_accounts_uid'), 'c_ad_accounts', ['uid'], unique=False)
    op.create_table('c_ad_ci_type_relations',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_type_id', sa.Integer(), nullable=False),
    sa.Column('ad_key', sa.String(length=128), nullable=True),
    sa.Column('peer_type_id', sa.Integer(), nullable=False),
    sa.Column('peer_attr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_type_id'], ['c_ci_types.id'], ),
    sa.ForeignKeyConstraint(['peer_attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['peer_type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_ci_type_relations_deleted'), 'c_ad_ci_type_relations', ['deleted'], unique=False)
    op.create_table('c_ad_ci_types',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('adr_id', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('relation', sa.JSON(), nullable=True),
    sa.Column('auto_accept', sa.Boolean(), nullable=True),
    sa.Column('agent_id', sa.String(length=8), nullable=True),
    sa.Column('query_expr', sa.Text(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('cron', sa.String(length=128), nullable=True),
    sa.Column('extra_option', sa.JSON(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['adr_id'], ['c_ad_rules.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_ci_types_agent_id'), 'c_ad_ci_types', ['agent_id'], unique=False)
    op.create_index(op.f('ix_c_ad_ci_types_deleted'), 'c_ad_ci_types', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ad_ci_types_uid'), 'c_ad_ci_types', ['uid'], unique=False)
    op.create_table('c_attribute_histories',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operate_type', sa.Enum('0', '1', '2', name='operate_type', native_enum=False), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('old', sa.Text(), nullable=True),
    sa.Column('new', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['c_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_attribute_histories_attr_id'), 'c_attribute_histories', ['attr_id'], unique=False)
    op.create_index(op.f('ix_c_attribute_histories_ci_id'), 'c_attribute_histories', ['ci_id'], unique=False)
    op.create_index(op.f('ix_c_attribute_histories_deleted'), 'c_attribute_histories', ['deleted'], unique=False)
    op.create_table('c_c_d',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.SmallInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('builtin_attr', sa.String(length=256), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_c_d_deleted'), 'c_c_d', ['deleted'], unique=False)
    op.create_table('c_c_t_t',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('notify', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_c_t_t_deleted'), 'c_c_t_t', ['deleted'], unique=False)
    op.create_table('c_c_t_u_c',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('attr_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_c_t_u_c_deleted'), 'c_c_t_u_c', ['deleted'], unique=False)
    op.create_table('c_choice_floats',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=53), nullable=False),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_choice_floats_deleted'), 'c_choice_floats', ['deleted'], unique=False)
    op.create_table('c_choice_integers',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_choice_integers_deleted'), 'c_choice_integers', ['deleted'], unique=False)
    op.create_table('c_choice_texts',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_choice_texts_deleted'), 'c_choice_texts', ['deleted'], unique=False)
    op.create_table('c_ci_filter_perms',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('ci_filter', sa.Text(), nullable=True),
    sa.Column('attr_filter', sa.Text(), nullable=True),
    sa.Column('id_filter', sa.JSON(), nullable=True),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_filter_perms_deleted'), 'c_ci_filter_perms', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ci_filter_perms_name'), 'c_ci_filter_perms', ['name'], unique=False)
    op.create_index(op.f('ix_c_ci_filter_perms_rid'), 'c_ci_filter_perms', ['rid'], unique=False)
    op.create_table('c_ci_type_attribute_groups',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_attribute_groups_deleted'), 'c_ci_type_attribute_groups', ['deleted'], unique=False)
    op.create_table('c_ci_type_attributes',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_show', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_attributes_deleted'), 'c_ci_type_attributes', ['deleted'], unique=False)
    op.create_table('c_ci_type_group_items',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['c_ci_type_groups.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_group_items_deleted'), 'c_ci_type_group_items', ['deleted'], unique=False)
    op.create_table('c_ci_type_inheritance',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['c_ci_types.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_inheritance_deleted'), 'c_ci_type_inheritance', ['deleted'], unique=False)
    op.create_table('c_ci_type_relations',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=False),
    sa.Column('constraint', sa.Enum('0', '1', '2', native_enum=False), nullable=True),
    sa.Column('parent_attr_id', sa.Integer(), nullable=True),
    sa.Column('child_attr_id', sa.Integer(), nullable=True),
    sa.Column('parent_attr_ids', sa.JSON(), nullable=True),
    sa.Column('child_attr_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['child_attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['c_ci_types.id'], ),
    sa.ForeignKeyConstraint(['parent_attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['c_ci_types.id'], ),
    sa.ForeignKeyConstraint(['relation_type_id'], ['c_relation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_relations_deleted'), 'c_ci_type_relations', ['deleted'], unique=False)
    op.create_table('c_cis',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('0', '1', name='status', native_enum=False), nullable=True),
    sa.Column('heartbeat', sa.DateTime(), nullable=True),
    sa.Column('a', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_cis_deleted'), 'c_cis', ['deleted'], unique=False)
    op.create_table('c_pcto',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.Column('is_tree', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_pcto_deleted'), 'c_pcto', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_pcto_uid'), 'c_pcto', ['uid'], unique=False)
    op.create_table('c_psa',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('builtin_attr', sa.String(length=256), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_psa_deleted'), 'c_psa', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_psa_uid'), 'c_psa', ['uid'], unique=False)
    op.create_table('c_ptv',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ptv_deleted'), 'c_ptv', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ptv_uid'), 'c_ptv', ['uid'], unique=False)
    op.create_table('c_relation_histories',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operate_type', sa.Enum('0', '1', name='operate_type', native_enum=False), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('first_ci_id', sa.Integer(), nullable=True),
    sa.Column('second_ci_id', sa.Integer(), nullable=True),
    sa.Column('relation_type_id', sa.Integer(), nullable=True),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['c_records.id'], ),
    sa.ForeignKeyConstraint(['relation_type_id'], ['c_relation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_relation_histories_deleted'), 'c_relation_histories', ['deleted'], unique=False)
    op.create_table('c_topology_views',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('central_node_type', sa.Integer(), nullable=True),
    sa.Column('central_node_instances', sa.Text(), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['c_topology_view_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_topology_views_deleted'), 'c_topology_views', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_topology_views_name'), 'c_topology_views', ['name'], unique=False)
    op.create_table('common_employee',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=64), nullable=True),
    sa.Column('position_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=255), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direct_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('acl_uid', sa.Integer(), nullable=True),
    sa.Column('acl_rid', sa.Integer(), nullable=True),
    sa.Column('acl_virtual_rid', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('notice_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['common_department.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_common_employee_deleted'), 'common_employee', ['deleted'], unique=False)
    op.create_table('acl_permissions',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['acl_resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_permissions_deleted'), 'acl_permissions', ['deleted'], unique=False)
    op.create_table('acl_resource_groups',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['acl_resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_resource_groups_deleted'), 'acl_resource_groups', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_resource_groups_name'), 'acl_resource_groups', ['name'], unique=False)
    op.create_index(op.f('ix_acl_resource_groups_uid'), 'acl_resource_groups', ['uid'], unique=False)
    op.create_table('acl_resources',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['acl_resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_resources_deleted'), 'acl_resources', ['deleted'], unique=False)
    op.create_index(op.f('ix_acl_resources_uid'), 'acl_resources', ['uid'], unique=False)
    op.create_table('acl_role_relations',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['acl_roles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['acl_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_role_relations_deleted'), 'acl_role_relations', ['deleted'], unique=False)
    op.create_table('acl_triggers',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('wildcard', sa.Text(), nullable=True),
    sa.Column('uid', sa.Text(), nullable=True),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['acl_resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_triggers_deleted'), 'acl_triggers', ['deleted'], unique=False)
    op.create_table('c_ad_ci',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('adt_id', sa.Integer(), nullable=True),
    sa.Column('unique_value', sa.String(length=128), nullable=True),
    sa.Column('instance', sa.JSON(), nullable=True),
    sa.Column('ci_id', sa.Integer(), nullable=True),
    sa.Column('is_accept', sa.Boolean(), nullable=True),
    sa.Column('accept_by', sa.String(length=64), nullable=True),
    sa.Column('accept_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adt_id'], ['c_ad_ci_types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_ci_accept_by'), 'c_ad_ci', ['accept_by'], unique=False)
    op.create_index(op.f('ix_c_ad_ci_ci_id'), 'c_ad_ci', ['ci_id'], unique=False)
    op.create_index(op.f('ix_c_ad_ci_deleted'), 'c_ad_ci', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_ad_ci_unique_value'), 'c_ad_ci', ['unique_value'], unique=False)
    op.create_table('c_ad_rule_sync_histories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adt_id', sa.Integer(), nullable=True),
    sa.Column('oneagent_id', sa.String(length=8), nullable=True),
    sa.Column('oneagent_name', sa.String(length=64), nullable=True),
    sa.Column('sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adt_id'], ['c_ad_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ad_rule_sync_histories_created_at'), 'c_ad_rule_sync_histories', ['created_at'], unique=False)
    op.create_table('c_ci_relations',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_ci_id', sa.Integer(), nullable=False),
    sa.Column('second_ci_id', sa.Integer(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=False),
    sa.Column('more', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('0', '1', name='source', native_enum=False), nullable=True),
    sa.Column('ancestor_ids', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['first_ci_id'], ['c_cis.id'], ),
    sa.ForeignKeyConstraint(['more'], ['c_cis.id'], ),
    sa.ForeignKeyConstraint(['relation_type_id'], ['c_relation_types.id'], ),
    sa.ForeignKeyConstraint(['second_ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_relations_ancestor_ids'), 'c_ci_relations', ['ancestor_ids'], unique=False)
    op.create_index(op.f('ix_c_ci_relations_deleted'), 'c_ci_relations', ['deleted'], unique=False)
    op.create_table('c_ci_trigger_histories',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operate_type', sa.Enum('0', '1', '2', name='operate_type', native_enum=False), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('trigger_name', sa.String(length=64), nullable=True),
    sa.Column('is_ok', sa.Boolean(), nullable=True),
    sa.Column('notify', sa.Text(), nullable=True),
    sa.Column('webhook', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['c_records.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['c_c_t_t.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_trigger_histories_ci_id'), 'c_ci_trigger_histories', ['ci_id'], unique=False)
    op.create_index(op.f('ix_c_ci_trigger_histories_deleted'), 'c_ci_trigger_histories', ['deleted'], unique=False)
    op.create_table('c_ci_type_attribute_group_items',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['c_ci_type_attribute_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_ci_type_attribute_group_items_deleted'), 'c_ci_type_attribute_group_items', ['deleted'], unique=False)
    op.create_table('c_pso',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('prv_id', sa.Integer(), nullable=True),
    sa.Column('ptv_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('option', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['prv_id'], ['c_prv.id'], ),
    sa.ForeignKeyConstraint(['ptv_id'], ['c_ptv.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['c_ci_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_pso_deleted'), 'c_pso', ['deleted'], unique=False)
    op.create_index(op.f('ix_c_pso_uid'), 'c_pso', ['uid'], unique=False)
    op.create_table('c_value_datetime',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_value_datetime_deleted'), 'c_value_datetime', ['deleted'], unique=False)
    op.create_table('c_value_floats',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_value_floats_deleted'), 'c_value_floats', ['deleted'], unique=False)
    op.create_table('c_value_index_datetime',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('datetime_attr_value_index', 'c_value_index_datetime', ['attr_id', 'value'], unique=False)
    op.create_index(op.f('ix_c_value_index_datetime_deleted'), 'c_value_index_datetime', ['deleted'], unique=False)
    op.create_table('c_value_index_floats',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('float_attr_value_index', 'c_value_index_floats', ['attr_id', 'value'], unique=False)
    op.create_index(op.f('ix_c_value_index_floats_deleted'), 'c_value_index_floats', ['deleted'], unique=False)
    op.create_table('c_value_index_integers',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('integer_attr_value_index', 'c_value_index_integers', ['attr_id', 'value'], unique=False)
    op.create_index(op.f('ix_c_value_index_integers_deleted'), 'c_value_index_integers', ['deleted'], unique=False)
    op.create_table('c_value_index_texts',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_value_index_texts_deleted'), 'c_value_index_texts', ['deleted'], unique=False)
    op.create_index('text_attr_value_index', 'c_value_index_texts', ['attr_id', 'value'], unique=False)
    op.create_table('c_value_integers',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_value_integers_deleted'), 'c_value_integers', ['deleted'], unique=False)
    op.create_table('c_value_json',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_value_json_deleted'), 'c_value_json', ['deleted'], unique=False)
    op.create_table('c_value_texts',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['c_attributes.id'], ),
    sa.ForeignKeyConstraint(['ci_id'], ['c_cis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c_value_texts_deleted'), 'c_value_texts', ['deleted'], unique=False)
    op.create_table('common_employee_info',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['common_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_employee_info_deleted'), 'common_employee_info', ['deleted'], unique=False)
    op.create_table('common_internal_message',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('category', sa.VARCHAR(length=128), nullable=False),
    sa.Column('message_data', sa.JSON(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True, comment='ID'),
    sa.ForeignKeyConstraint(['employee_id'], ['common_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_internal_message_deleted'), 'common_internal_message', ['deleted'], unique=False)
    op.create_table('acl_resource_group_items',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['acl_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['acl_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_resource_group_items_deleted'), 'acl_resource_group_items', ['deleted'], unique=False)
    op.create_table('acl_role_permissions',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('perm_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['acl_apps.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['acl_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['perm_id'], ['acl_permissions.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['acl_resources.id'], ),
    sa.ForeignKeyConstraint(['rid'], ['acl_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_role_permissions_deleted'), 'acl_role_permissions', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acl_role_permissions_deleted'), table_name='acl_role_permissions')
    op.drop_table('acl_role_permissions')
    op.drop_index(op.f('ix_acl_resource_group_items_deleted'), table_name='acl_resource_group_items')
    op.drop_table('acl_resource_group_items')
    op.drop_index(op.f('ix_common_internal_message_deleted'), table_name='common_internal_message')
    op.drop_table('common_internal_message')
    op.drop_index(op.f('ix_common_employee_info_deleted'), table_name='common_employee_info')
    op.drop_table('common_employee_info')
    op.drop_index(op.f('ix_c_value_texts_deleted'), table_name='c_value_texts')
    op.drop_table('c_value_texts')
    op.drop_index(op.f('ix_c_value_json_deleted'), table_name='c_value_json')
    op.drop_table('c_value_json')
    op.drop_index(op.f('ix_c_value_integers_deleted'), table_name='c_value_integers')
    op.drop_table('c_value_integers')
    op.drop_index('text_attr_value_index', table_name='c_value_index_texts')
    op.drop_index(op.f('ix_c_value_index_texts_deleted'), table_name='c_value_index_texts')
    op.drop_table('c_value_index_texts')
    op.drop_index(op.f('ix_c_value_index_integers_deleted'), table_name='c_value_index_integers')
    op.drop_index('integer_attr_value_index', table_name='c_value_index_integers')
    op.drop_table('c_value_index_integers')
    op.drop_index(op.f('ix_c_value_index_floats_deleted'), table_name='c_value_index_floats')
    op.drop_index('float_attr_value_index', table_name='c_value_index_floats')
    op.drop_table('c_value_index_floats')
    op.drop_index(op.f('ix_c_value_index_datetime_deleted'), table_name='c_value_index_datetime')
    op.drop_index('datetime_attr_value_index', table_name='c_value_index_datetime')
    op.drop_table('c_value_index_datetime')
    op.drop_index(op.f('ix_c_value_floats_deleted'), table_name='c_value_floats')
    op.drop_table('c_value_floats')
    op.drop_index(op.f('ix_c_value_datetime_deleted'), table_name='c_value_datetime')
    op.drop_table('c_value_datetime')
    op.drop_index(op.f('ix_c_pso_uid'), table_name='c_pso')
    op.drop_index(op.f('ix_c_pso_deleted'), table_name='c_pso')
    op.drop_table('c_pso')
    op.drop_index(op.f('ix_c_ci_type_attribute_group_items_deleted'), table_name='c_ci_type_attribute_group_items')
    op.drop_table('c_ci_type_attribute_group_items')
    op.drop_index(op.f('ix_c_ci_trigger_histories_deleted'), table_name='c_ci_trigger_histories')
    op.drop_index(op.f('ix_c_ci_trigger_histories_ci_id'), table_name='c_ci_trigger_histories')
    op.drop_table('c_ci_trigger_histories')
    op.drop_index(op.f('ix_c_ci_relations_deleted'), table_name='c_ci_relations')
    op.drop_index(op.f('ix_c_ci_relations_ancestor_ids'), table_name='c_ci_relations')
    op.drop_table('c_ci_relations')
    op.drop_index(op.f('ix_c_ad_rule_sync_histories_created_at'), table_name='c_ad_rule_sync_histories')
    op.drop_table('c_ad_rule_sync_histories')
    op.drop_index(op.f('ix_c_ad_ci_unique_value'), table_name='c_ad_ci')
    op.drop_index(op.f('ix_c_ad_ci_deleted'), table_name='c_ad_ci')
    op.drop_index(op.f('ix_c_ad_ci_ci_id'), table_name='c_ad_ci')
    op.drop_index(op.f('ix_c_ad_ci_accept_by'), table_name='c_ad_ci')
    op.drop_table('c_ad_ci')
    op.drop_index(op.f('ix_acl_triggers_deleted'), table_name='acl_triggers')
    op.drop_table('acl_triggers')
    op.drop_index(op.f('ix_acl_role_relations_deleted'), table_name='acl_role_relations')
    op.drop_table('acl_role_relations')
    op.drop_index(op.f('ix_acl_resources_uid'), table_name='acl_resources')
    op.drop_index(op.f('ix_acl_resources_deleted'), table_name='acl_resources')
    op.drop_table('acl_resources')
    op.drop_index(op.f('ix_acl_resource_groups_uid'), table_name='acl_resource_groups')
    op.drop_index(op.f('ix_acl_resource_groups_name'), table_name='acl_resource_groups')
    op.drop_index(op.f('ix_acl_resource_groups_deleted'), table_name='acl_resource_groups')
    op.drop_table('acl_resource_groups')
    op.drop_index(op.f('ix_acl_permissions_deleted'), table_name='acl_permissions')
    op.drop_table('acl_permissions')
    op.drop_index(op.f('ix_common_employee_deleted'), table_name='common_employee')
    op.drop_table('common_employee')
    op.drop_index(op.f('ix_c_topology_views_name'), table_name='c_topology_views')
    op.drop_index(op.f('ix_c_topology_views_deleted'), table_name='c_topology_views')
    op.drop_table('c_topology_views')
    op.drop_index(op.f('ix_c_relation_histories_deleted'), table_name='c_relation_histories')
    op.drop_table('c_relation_histories')
    op.drop_index(op.f('ix_c_ptv_uid'), table_name='c_ptv')
    op.drop_index(op.f('ix_c_ptv_deleted'), table_name='c_ptv')
    op.drop_table('c_ptv')
    op.drop_index(op.f('ix_c_psa_uid'), table_name='c_psa')
    op.drop_index(op.f('ix_c_psa_deleted'), table_name='c_psa')
    op.drop_table('c_psa')
    op.drop_index(op.f('ix_c_pcto_uid'), table_name='c_pcto')
    op.drop_index(op.f('ix_c_pcto_deleted'), table_name='c_pcto')
    op.drop_table('c_pcto')
    op.drop_index(op.f('ix_c_cis_deleted'), table_name='c_cis')
    op.drop_table('c_cis')
    op.drop_index(op.f('ix_c_ci_type_relations_deleted'), table_name='c_ci_type_relations')
    op.drop_table('c_ci_type_relations')
    op.drop_index(op.f('ix_c_ci_type_inheritance_deleted'), table_name='c_ci_type_inheritance')
    op.drop_table('c_ci_type_inheritance')
    op.drop_index(op.f('ix_c_ci_type_group_items_deleted'), table_name='c_ci_type_group_items')
    op.drop_table('c_ci_type_group_items')
    op.drop_index(op.f('ix_c_ci_type_attributes_deleted'), table_name='c_ci_type_attributes')
    op.drop_table('c_ci_type_attributes')
    op.drop_index(op.f('ix_c_ci_type_attribute_groups_deleted'), table_name='c_ci_type_attribute_groups')
    op.drop_table('c_ci_type_attribute_groups')
    op.drop_index(op.f('ix_c_ci_filter_perms_rid'), table_name='c_ci_filter_perms')
    op.drop_index(op.f('ix_c_ci_filter_perms_name'), table_name='c_ci_filter_perms')
    op.drop_index(op.f('ix_c_ci_filter_perms_deleted'), table_name='c_ci_filter_perms')
    op.drop_table('c_ci_filter_perms')
    op.drop_index(op.f('ix_c_choice_texts_deleted'), table_name='c_choice_texts')
    op.drop_table('c_choice_texts')
    op.drop_index(op.f('ix_c_choice_integers_deleted'), table_name='c_choice_integers')
    op.drop_table('c_choice_integers')
    op.drop_index(op.f('ix_c_choice_floats_deleted'), table_name='c_choice_floats')
    op.drop_table('c_choice_floats')
    op.drop_index(op.f('ix_c_c_t_u_c_deleted'), table_name='c_c_t_u_c')
    op.drop_table('c_c_t_u_c')
    op.drop_index(op.f('ix_c_c_t_t_deleted'), table_name='c_c_t_t')
    op.drop_table('c_c_t_t')
    op.drop_index(op.f('ix_c_c_d_deleted'), table_name='c_c_d')
    op.drop_table('c_c_d')
    op.drop_index(op.f('ix_c_attribute_histories_deleted'), table_name='c_attribute_histories')
    op.drop_index(op.f('ix_c_attribute_histories_ci_id'), table_name='c_attribute_histories')
    op.drop_index(op.f('ix_c_attribute_histories_attr_id'), table_name='c_attribute_histories')
    op.drop_table('c_attribute_histories')
    op.drop_index(op.f('ix_c_ad_ci_types_uid'), table_name='c_ad_ci_types')
    op.drop_index(op.f('ix_c_ad_ci_types_deleted'), table_name='c_ad_ci_types')
    op.drop_index(op.f('ix_c_ad_ci_types_agent_id'), table_name='c_ad_ci_types')
    op.drop_table('c_ad_ci_types')
    op.drop_index(op.f('ix_c_ad_ci_type_relations_deleted'), table_name='c_ad_ci_type_relations')
    op.drop_table('c_ad_ci_type_relations')
    op.drop_index(op.f('ix_c_ad_accounts_uid'), table_name='c_ad_accounts')
    op.drop_index(op.f('ix_c_ad_accounts_deleted'), table_name='c_ad_accounts')
    op.drop_table('c_ad_accounts')
    op.drop_index(op.f('ix_acl_roles_name'), table_name='acl_roles')
    op.drop_index(op.f('ix_acl_roles_deleted'), table_name='acl_roles')
    op.drop_table('acl_roles')
    op.drop_index(op.f('ix_acl_resource_types_name'), table_name='acl_resource_types')
    op.drop_index(op.f('ix_acl_resource_types_deleted'), table_name='acl_resource_types')
    op.drop_table('acl_resource_types')
    op.drop_index(op.f('ix_common_notice_config_deleted'), table_name='common_notice_config')
    op.drop_table('common_notice_config')
    op.drop_index(op.f('ix_common_file_file_name'), table_name='common_file')
    op.drop_index(op.f('ix_common_file_deleted'), table_name='common_file')
    op.drop_table('common_file')
    op.drop_index(op.f('ix_common_department_deleted'), table_name='common_department')
    op.drop_table('common_department')
    op.drop_index(op.f('ix_common_data_deleted'), table_name='common_data')
    op.drop_table('common_data')
    op.drop_index(op.f('ix_common_company_info_json_deleted'), table_name='common_company_info_json')
    op.drop_table('common_company_info_json')
    op.drop_index(op.f('ix_c_topology_view_groups_name'), table_name='c_topology_view_groups')
    op.drop_index(op.f('ix_c_topology_view_groups_deleted'), table_name='c_topology_view_groups')
    op.drop_table('c_topology_view_groups')
    op.drop_index(op.f('ix_c_sc_name'), table_name='c_sc')
    op.drop_index(op.f('ix_c_sc_deleted'), table_name='c_sc')
    op.drop_table('c_sc')
    op.drop_index(op.f('ix_c_relation_types_name'), table_name='c_relation_types')
    op.drop_index(op.f('ix_c_relation_types_deleted'), table_name='c_relation_types')
    op.drop_table('c_relation_types')
    op.drop_index(op.f('ix_c_records_uid'), table_name='c_records')
    op.drop_index(op.f('ix_c_records_type_id'), table_name='c_records')
    op.drop_index(op.f('ix_c_records_created_at'), table_name='c_records')
    op.drop_table('c_records')
    op.drop_index(op.f('ix_c_prv_uid'), table_name='c_prv')
    op.drop_index(op.f('ix_c_prv_name'), table_name='c_prv')
    op.drop_index(op.f('ix_c_prv_deleted'), table_name='c_prv')
    op.drop_table('c_prv')
    op.drop_index(op.f('ix_c_pasc_uid'), table_name='c_pasc')
    op.drop_index(op.f('ix_c_pasc_deleted'), table_name='c_pasc')
    op.drop_table('c_pasc')
    op.drop_index(op.f('ix_c_kv_key'), table_name='c_kv')
    op.drop_index(op.f('ix_c_kv_deleted'), table_name='c_kv')
    op.drop_table('c_kv')
    op.drop_index(op.f('ix_c_ipam_subnet_scans_deleted'), table_name='c_ipam_subnet_scans')
    op.drop_index(op.f('ix_c_ipam_subnet_scans_ci_id'), table_name='c_ipam_subnet_scans')
    op.drop_index(op.f('ix_c_ipam_subnet_scans_agent_id'), table_name='c_ipam_subnet_scans')
    op.drop_table('c_ipam_subnet_scans')
    op.drop_index(op.f('ix_c_ipam_subnet_scan_histories_subnet_scan_id'), table_name='c_ipam_subnet_scan_histories')
    op.drop_index(op.f('ix_c_ipam_subnet_scan_histories_exec_id'), table_name='c_ipam_subnet_scan_histories')
    op.drop_index(op.f('ix_c_ipam_subnet_scan_histories_created_at'), table_name='c_ipam_subnet_scan_histories')
    op.drop_index(op.f('ix_c_ipam_subnet_scan_histories_cidr'), table_name='c_ipam_subnet_scan_histories')
    op.drop_table('c_ipam_subnet_scan_histories')
    op.drop_index(op.f('ix_c_ipam_operation_histories_uid'), table_name='c_ipam_operation_histories')
    op.drop_index(op.f('ix_c_ipam_operation_histories_created_at'), table_name='c_ipam_operation_histories')
    op.drop_index(op.f('ix_c_ipam_operation_histories_cidr'), table_name='c_ipam_operation_histories')
    op.drop_table('c_ipam_operation_histories')
    op.drop_index(op.f('ix_c_dcim_operation_histories_uid'), table_name='c_dcim_operation_histories')
    op.drop_index(op.f('ix_c_dcim_operation_histories_rack_id'), table_name='c_dcim_operation_histories')
    op.drop_index(op.f('ix_c_dcim_operation_histories_created_at'), table_name='c_dcim_operation_histories')
    op.drop_index(op.f('ix_c_dcim_operation_histories_ci_id'), table_name='c_dcim_operation_histories')
    op.drop_table('c_dcim_operation_histories')
    op.drop_constraint('fk_c_attributes_reference_type_id_c_ci_types', 'c_attributes', type_='foreignkey')
    op.drop_index(op.f('ix_c_ci_types_uid'), table_name='c_ci_types')
    op.drop_index(op.f('ix_c_ci_types_deleted'), table_name='c_ci_types')
    op.drop_table('c_ci_types')
    op.drop_index(op.f('ix_c_ci_type_histories_uid'), table_name='c_ci_type_histories')
    op.drop_index(op.f('ix_c_ci_type_histories_type_id'), table_name='c_ci_type_histories')
    op.drop_index(op.f('ix_c_ci_type_histories_deleted'), table_name='c_ci_type_histories')
    op.drop_table('c_ci_type_histories')
    op.drop_index(op.f('ix_c_ci_type_groups_deleted'), table_name='c_ci_type_groups')
    op.drop_table('c_ci_type_groups')
    op.drop_index(op.f('ix_c_attributes_uid'), table_name='c_attributes')
    op.drop_index(op.f('ix_c_attributes_deleted'), table_name='c_attributes')
    op.drop_table('c_attributes')
    op.drop_index(op.f('ix_c_ad_rules_type'), table_name='c_ad_rules')
    op.drop_index(op.f('ix_c_ad_rules_owner'), table_name='c_ad_rules')
    op.drop_index(op.f('ix_c_ad_rules_is_inner'), table_name='c_ad_rules')
    op.drop_index(op.f('ix_c_ad_rules_deleted'), table_name='c_ad_rules')
    op.drop_table('c_ad_rules')
    op.drop_index(op.f('ix_c_ad_exec_histories_type_id'), table_name='c_ad_exec_histories')
    op.drop_index(op.f('ix_c_ad_exec_histories_created_at'), table_name='c_ad_exec_histories')
    op.drop_table('c_ad_exec_histories')
    op.drop_index(op.f('ix_c_ad_counter_type_id'), table_name='c_ad_counter')
    op.drop_index(op.f('ix_c_ad_counter_created_at'), table_name='c_ad_counter')
    op.drop_table('c_ad_counter')
    op.drop_index(op.f('ix_acl_operation_records_rolename'), table_name='acl_operation_records')
    op.drop_index(op.f('ix_acl_operation_records_deleted'), table_name='acl_operation_records')
    op.drop_index(op.f('ix_acl_operation_records_app'), table_name='acl_operation_records')
    op.drop_table('acl_operation_records')
    op.drop_index(op.f('ix_acl_audit_trigger_logs_trigger_id'), table_name='acl_audit_trigger_logs')
    op.drop_index(op.f('ix_acl_audit_trigger_logs_operate_uid'), table_name='acl_audit_trigger_logs')
    op.drop_index(op.f('ix_acl_audit_trigger_logs_operate_type'), table_name='acl_audit_trigger_logs')
    op.drop_index(op.f('ix_acl_audit_trigger_logs_deleted'), table_name='acl_audit_trigger_logs')
    op.drop_index(op.f('ix_acl_audit_trigger_logs_app_id'), table_name='acl_audit_trigger_logs')
    op.drop_table('acl_audit_trigger_logs')
    op.drop_index(op.f('ix_acl_audit_role_logs_operate_uid'), table_name='acl_audit_role_logs')
    op.drop_index(op.f('ix_acl_audit_role_logs_operate_type'), table_name='acl_audit_role_logs')
    op.drop_index(op.f('ix_acl_audit_role_logs_link_id'), table_name='acl_audit_role_logs')
    op.drop_index(op.f('ix_acl_audit_role_logs_deleted'), table_name='acl_audit_role_logs')
    op.drop_index(op.f('ix_acl_audit_role_logs_app_id'), table_name='acl_audit_role_logs')
    op.drop_table('acl_audit_role_logs')
    op.drop_index(op.f('ix_acl_audit_resource_logs_operate_uid'), table_name='acl_audit_resource_logs')
    op.drop_index(op.f('ix_acl_audit_resource_logs_operate_type'), table_name='acl_audit_resource_logs')
    op.drop_index(op.f('ix_acl_audit_resource_logs_link_id'), table_name='acl_audit_resource_logs')
    op.drop_index(op.f('ix_acl_audit_resource_logs_deleted'), table_name='acl_audit_resource_logs')
    op.drop_index(op.f('ix_acl_audit_resource_logs_app_id'), table_name='acl_audit_resource_logs')
    op.drop_table('acl_audit_resource_logs')
    op.drop_index(op.f('ix_acl_audit_permission_logs_rid'), table_name='acl_audit_permission_logs')
    op.drop_index(op.f('ix_acl_audit_permission_logs_resource_type_id'), table_name='acl_audit_permission_logs')
    op.drop_index(op.f('ix_acl_audit_permission_logs_operate_uid'), table_name='acl_audit_permission_logs')
    op.drop_index(op.f('ix_acl_audit_permission_logs_operate_type'), table_name='acl_audit_permission_logs')
    op.drop_index(op.f('ix_acl_audit_permission_logs_deleted'), table_name='acl_audit_permission_logs')
    op.drop_index(op.f('ix_acl_audit_permission_logs_app_id'), table_name='acl_audit_permission_logs')
    op.drop_table('acl_audit_permission_logs')
    op.drop_index(op.f('ix_acl_audit_login_logs_username'), table_name='acl_audit_login_logs')
    op.drop_index(op.f('ix_acl_audit_login_logs_created_at'), table_name='acl_audit_login_logs')
    op.drop_table('acl_audit_login_logs')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_acl_apps_name'), table_name='acl_apps')
    op.drop_index(op.f('ix_acl_apps_deleted'), table_name='acl_apps')
    op.drop_table('acl_apps')
    # ### end Alembic commands ###
